import re
import json
import sys
import time
from openai import OpenAI
from src.rerankers.base import BaseReranker

class LLMReranker(BaseReranker):
    def __init__(self, model_name: str, base_url: str, api_key: str):
        self.model_name = model_name
        self.client = OpenAI(api_key=api_key, base_url=base_url)

    def rerank(self, query: str, candidates: list, top_n: int = 10) -> list:
        if not candidates:
            return []

        print(f"   └─ Reranking candidate pool with {self.model_name}... ", end="", flush=True)
        start_time = time.time()

        candidates_block = ""
        id_map = {}

        for idx, commit in enumerate(candidates[:10]):
            temp_id = f"DOC_{idx}"
            id_map[temp_id] = commit

            summary = commit.get("summary", "")
            message = commit.get("message", "")

            short_message = message[:250].replace('\n', ' ').strip()
            candidates_block += f"[{temp_id}] Summary: {summary} | Details: {short_message}...\n"

        prompt = f"""You are an expert system optimizing a software engineering search engine.
User Search Query: "{query}"

Below are 10 candidate git commits generated by a keyword index. Rank them based on how accurately they resolve the user's intent.

{candidates_block}
Task: Sort the document IDs from most relevant to least relevant.
Output format: Return ONLY a valid JSON array of strings containing the ordered IDs, like this: ["DOC_4", "DOC_1", "DOC_0", ...]
Do not include any conversational introduction, explanation, or markdown wrappers outside the raw JSON."""

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0
            )
            content = response.choices[0].message.content or ""
            elapsed_time = time.time() - start_time

            if not content.strip():
                print(f"FAILED ({elapsed_time:.2f}s) - Empty completion", file=sys.stderr)
                return candidates[:top_n]

            start_idx = content.find("[")
            end_idx = content.rfind("]")

            if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
                print(f"FAILED ({elapsed_time:.2f}s) - Invalid structural boundaries", file=sys.stderr)
                return candidates[:top_n]

            clean_json = content[start_idx:end_idx + 1]

            try:
                ordered_ids = json.loads(clean_json)
            except json.JSONDecodeError:
                print(f"FAILED ({elapsed_time:.2f}s) - Substring syntax compilation error", file=sys.stderr)
                return candidates[:top_n]

            if not isinstance(ordered_ids, list) or not ordered_ids:
                print(f"FAILED ({elapsed_time:.2f}s) - Returned object mismatch", file=sys.stderr)
                return candidates[:top_n]

            seen_ids = set()
            valid_ordered_ids = []

            for tid in ordered_ids:
                if not isinstance(tid, str) or tid not in id_map or tid in seen_ids:
                    continue
                seen_ids.add(tid)
                valid_ordered_ids.append(tid)

            reranked_results = [id_map[tid] for tid in valid_ordered_ids]

            for tid, commit in id_map.items():
                if commit not in reranked_results:
                    reranked_results.append(commit)

            for commit in candidates[10:]:
                if commit not in reranked_results:
                    reranked_results.append(commit)

            print(f"SUCCESS ({elapsed_time:.2f}s) | Ordered: {valid_ordered_ids[:3]}...")
            return reranked_results[:top_n]

        except Exception as e:
            elapsed_time = time.time() - start_time
            print(f"CRASHED ({elapsed_time:.2f}s) - {str(e)}", file=sys.stderr)
            return candidates[:top_n]
