import re
import json
from openai import OpenAI
from src.rerankers.base import BaseReranker

class LLMReranker(BaseReranker):
    def __init__(self, model_name: str, base_url: str):
        self.model_name = model_name
        self.client = OpenAI(api_key="ollama", base_url=base_url)

    def rerank(self, query: str, candidates: list, top_n: int = 10) -> list:
        if not candidates:
            return []

        candidates_block = ""
        id_map = {}
        for idx, commit in enumerate(candidates[:15]):
            temp_id = f"DOC_{idx}"
            id_map[temp_id] = commit
            candidates_block += f"[{temp_id}] Summary: {commit['summary']}\nMessage: {commit['message']}\n\n"

        prompt = f"""You are an expert system optimizing a software engineering search engine.
User Search Query: "{query}"

Below are 15 candidate git commits generated by a keyword index. Rank them based on how accurately they resolve the user's intent.

{candidates_block}
Task: Sort the document IDs from most relevant to least relevant.
Output format: Return ONLY a valid JSON array of strings containing the ordered IDs, like this: ["DOC_4", "DOC_1", "DOC_0", ...]
Do not include any conversational introduction, explanation, or markdown wrappers outside the raw JSON."""

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0
            )
            content = response.choices[0].message.content or ""

            clean_json = re.sub(r"```json|```", "", content).strip()
            ordered_ids = json.loads(clean_json)

            reranked_results = [id_map[tid] for tid in ordered_ids if tid in id_map]

            for tid, commit in id_map.items():
                if commit not in reranked_results:
                    reranked_results.append(commit)

            return reranked_results[:top_n]

        except Exception as e:
            return candidates[:top_n]
